import os

def build(bld):
    obj = bld.create_ns3_program('routing', bld.env['NS3_ENABLED_MODULES'])
    obj.source  = ['routing.cc']
    obj.lib     = ['oqs', 'ssl', 'crypto']
    obj.libpath = ['/usr/local/lib']
    obj.rpath   = ['/usr/local/lib']
